# Generated by Django 5.1.4 on 2024-12-24 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TeachersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LessonsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('groups', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='najot.groupsmodel')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworksModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField()),
                ('lesson', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='najot.lessonsmodel')),
            ],
        ),
        migrations.AddField(
            model_name='groupsmodel',
            name='students',
            field=models.ManyToManyField(to='najot.studentsmodel'),
        ),
        migrations.AddField(
            model_name='groupsmodel',
            name='teacher',
            field=models.ManyToManyField(to='najot.teachersmodel'),
        ),
    ]
