# Generated by Django 5.1.4 on 2025-01-06 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('najot', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestFormModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='test')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupsmodel',
            name='students',
        ),
        migrations.RemoveField(
            model_name='groupsmodel',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='lessonsmodel',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='homeworksmodel',
            name='lesson',
        ),
        migrations.DeleteModel(
            name='StudentsModel',
        ),
        migrations.DeleteModel(
            name='TeachersModel',
        ),
        migrations.DeleteModel(
            name='GroupsModel',
        ),
        migrations.DeleteModel(
            name='HomeworksModel',
        ),
        migrations.DeleteModel(
            name='LessonsModel',
        ),
    ]
