# Generated by Django 5.1.4 on 2024-12-24 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_authorsmodel_alter_blogsmodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='authorsmodel',
            options={'verbose_name': 'author', 'verbose_name_plural': 'authors'},
        ),
        migrations.AlterModelOptions(
            name='blogsmodel',
            options={'verbose_name': 'blog', 'verbose_name_plural': 'blogs'},
        ),
        migrations.AlterModelTable(
            name='blogsmodel',
            table=None,
        ),
    ]
